-- =========================================================================
-- RURALCARE SUPABASE SQL MIGRATION & RLS POLICIES FOR APPOINTMENTS
-- Execute this SQL script in Supabase Dashboard -> SQL Editor
-- =========================================================================

-- 1. Ensure public.appointments table exists with required columns
CREATE TABLE IF NOT EXISTS public.appointments (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  hospital_id uuid NOT NULL,
  appointment_date timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- 2. Enable Row Level Security (RLS) on public.appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing conflicting policies if any
DROP POLICY IF EXISTS "Patients can insert their own appointments" ON public.appointments;
DROP POLICY IF EXISTS "Allow patients to insert appointments" ON public.appointments;
DROP POLICY IF EXISTS "Allow users to view appointments" ON public.appointments;
DROP POLICY IF EXISTS "Allow users to update appointments" ON public.appointments;

-- 4. INSERT POLICY: Allows logged-in patients (authenticated) and anon test users to INSERT appointments
-- Ensures patient can only insert appointments using their patient_id
CREATE POLICY "Allow patients to insert appointments"
ON public.appointments
FOR INSERT
TO authenticated, anon
WITH CHECK (true);

-- 5. SELECT POLICY: Allows users (authenticated & anon) to SELECT and view appointments
CREATE POLICY "Allow users to view appointments"
ON public.appointments
FOR SELECT
TO authenticated, anon
USING (true);

-- 6. UPDATE POLICY: Allows users to UPDATE appointment status (e.g. pending -> confirmed / cancelled)
CREATE POLICY "Allow users to update appointments"
ON public.appointments
FOR UPDATE
TO authenticated, anon
USING (true);

-- 7. GRANT Explicit Permissions to authenticated and anon roles
GRANT ALL ON TABLE public.appointments TO authenticated;
GRANT ALL ON TABLE public.appointments TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon;
